"""add role to users

Revision ID: b4cbac6905e4
Revises: 80e6e6649df7
Create Date: 2026-01-16 13:02:03.417575

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4cbac6905e4"
down_revision: str | Sequence[str] | None = "80e6e6649df7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("role", sa.String(length=10), nullable=False, server_default="user"),
    )

    op.execute(
        "ALTER TABLE users ADD CONSTRAINT check_role CHECK (role IN ('admin', 'user'))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS check_role")
    op.drop_column("users", "role")
    # ### end Alembic commands ###
